#!/usr/bin/env bash
# Millicall PBX — One-line installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/mizphses/millicall/main/install.sh | bash
#
set -euo pipefail

REPO="https://github.com/mizphses/millicall.git"
INSTALL_DIR="${MILLICALL_DIR:-$HOME/millicall}"

echo ""
echo "  ┌─────────────────────────────────┐"
echo "  │     Millicall PBX Installer      │"
echo "  └─────────────────────────────────┘"
echo ""

# --- Check dependencies ---
check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        echo "  [!] $1 が見つかりません。"
        return 1
    fi
    return 0
}

# Docker check
if ! check_cmd docker; then
    echo ""
    echo "  Docker をインストールしてください:"
    echo "    curl -fsSL https://get.docker.com | sh"
    echo "    sudo usermod -aG docker \$USER"
    echo "    newgrp docker"
    echo ""
    echo "  インストール後、このスクリプトを再実行してください。"
    exit 1
fi

if ! docker compose version &>/dev/null 2>&1; then
    echo "  [!] docker compose プラグインが見つかりません。"
    echo "  Docker を最新版に更新してください。"
    exit 1
fi

# Git check
if ! check_cmd git; then
    echo "  [!] git をインストールしてください: sudo apt install git"
    exit 1
fi

echo "  [1/4] リポジトリをクローン中..."
if [ -d "$INSTALL_DIR" ]; then
    echo "        $INSTALL_DIR は既に存在します。pullします..."
    cd "$INSTALL_DIR"
    git pull --quiet
else
    git clone --quiet "$REPO" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi
echo ""

# --- Interactive setup ---
gen_secret() { python3 -c "import secrets; print(secrets.token_urlsafe($1))" 2>/dev/null || openssl rand -base64 "$1" | tr -d '=/+' | head -c "$1"; }

echo "  [2/4] セットアップ"
echo ""

# Admin password
read -rp "  管理者パスワード (空欄で自動生成): " ADMIN_PASSWORD
if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD=$(gen_secret 16)
    echo "  -> 生成しました: $ADMIN_PASSWORD"
fi
echo ""

# LLM keys
echo "  AI機能で使うAPIキー (あとでWebUIからも設定可能)"
read -rp "  Google AI API Key (空欄でスキップ): " GOOGLE_API_KEY
read -rp "  OpenAI API Key (空欄でスキップ): " OPENAI_API_KEY
echo ""

# Cloudflare Tunnel
read -rp "  Cloudflare Tunnel を使いますか? [y/N]: " USE_TUNNEL
TUNNEL_TOKEN=""
TUNNEL_PROFILE=""
if [[ "$USE_TUNNEL" =~ ^[Yy]$ ]]; then
    echo ""
    echo "  トークン取得: https://one.dash.cloudflare.com/ > Networks > Tunnels"
    read -rp "  Tunnel Token (あとで設定する場合は空欄): " TUNNEL_TOKEN
    if [ -n "$TUNNEL_TOKEN" ]; then
        TUNNEL_PROFILE="--profile tunnel"
    fi
fi
echo ""

# --- Generate .env ---
echo "  [3/4] 設定ファイルを生成中..."

cat > .env <<EOF
# Millicall PBX — auto-generated by installer
JWT_SECRET=$(gen_secret 64)
ADMIN_PASSWORD=${ADMIN_PASSWORD}
WEBRTC_PASSWORD=$(gen_secret 16)
ARI_USER=millicall
ARI_PASSWORD=$(gen_secret 16)
GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=
CLOUDFLARE_TUNNEL_TOKEN=${TUNNEL_TOKEN:-}
EOF
chmod 600 .env
echo "  -> .env を生成しました"
echo ""

# --- Build and start ---
echo "  [4/4] ビルド・起動中... (初回は数分かかります)"
echo ""
# shellcheck disable=SC2086
docker compose $TUNNEL_PROFILE up -d --build

echo ""
echo "  ┌─────────────────────────────────┐"
echo "  │       セットアップ完了!          │"
echo "  └─────────────────────────────────┘"
echo ""
echo "  Web UI:   http://localhost"
echo "  ユーザー: admin"
echo "  パスワード: $ADMIN_PASSWORD"
echo ""
echo "  インストール先: $INSTALL_DIR"
echo ""
echo "  便利なコマンド:"
echo "    cd $INSTALL_DIR"
echo "    docker compose logs -f    # ログ確認"
echo "    docker compose restart    # 再起動"
echo "    docker compose down       # 停止"
echo ""
