"""Millicall PBX CLI — interactive setup and management.

Usage:
    millicall setup         Interactive setup wizard
    millicall start         Start all services
    millicall stop          Stop all services
    millicall logs          Show logs
    millicall status        Show service status
    millicall generate-config  Generate Asterisk config from DB
"""

import asyncio
import contextlib
import logging
import secrets
import shutil
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Callable

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _find_compose() -> list[str]:
    if shutil.which("docker"):
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return ["docker", "compose"]
    if shutil.which("docker-compose"):
        return ["docker-compose"]
    return []


def _run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=PROJECT_ROOT, **kwargs)


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    answer = input(f"{prompt}{suffix}: ").strip()
    return answer or default


def _ask_yn(prompt: str, default: bool = True) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    answer = input(f"{prompt}{suffix}: ").strip().lower()
    if not answer:
        return default
    return answer in ("y", "yes")


def _secret(length: int = 16) -> str:
    return secrets.token_urlsafe(length)


def _print_banner() -> None:
    print("")
    print("  ┌─────────────────────────────────┐")
    print("  │       Millicall PBX Setup        │")
    print("  └─────────────────────────────────┘")
    print("")


def _print_step(n: int, total: int, msg: str) -> None:
    print(f"  [{n}/{total}] {msg}")
    print("")


# ---------------------------------------------------------------------------
# Setup wizard
# ---------------------------------------------------------------------------


def cmd_setup() -> None:
    """Interactive setup wizard."""
    _print_banner()

    env_path = PROJECT_ROOT / ".env"
    if env_path.exists() and not _ask_yn("  .env が既に存在します。上書きしますか?", default=False):
        print("  既存の .env を使用します。")
        _maybe_start()
        return

    total_steps = 4
    env_lines: list[str] = [
        "# Millicall PBX — Environment Variables",
        "# Generated by: millicall setup",
        "",
    ]

    # --- Step 1: Admin password ---
    _print_step(1, total_steps, "管理者アカウント")
    admin_password = _ask("  管理者パスワード (空欄で自動生成)")
    if not admin_password:
        admin_password = _secret()
        print(f"  -> 生成しました: {admin_password}")
    print("")

    env_lines += [
        "# --- Security ---",
        f"JWT_SECRET={_secret(64)}",
        f"ADMIN_PASSWORD={admin_password}",
        f"WEBRTC_PASSWORD={_secret()}",
        "",
        "# --- ARI ---",
        "ARI_USER=millicall",
        f"ARI_PASSWORD={_secret()}",
        "",
    ]

    # --- Step 2: LLM API keys ---
    _print_step(2, total_steps, "AI機能 (電話応対AI・ワークフロー)")
    print("  利用するLLMのAPIキーを設定します。")
    print("  あとからWebUIの設定画面でも変更できます。")
    print("")

    google_key = _ask("  Google AI API Key (空欄でスキップ)")
    openai_key = _ask("  OpenAI API Key (空欄でスキップ)")
    anthropic_key = _ask("  Anthropic API Key (空欄でスキップ)")
    print("")

    env_lines += [
        "# --- LLM API Keys ---",
        f"GOOGLE_API_KEY={google_key}",
        f"OPENAI_API_KEY={openai_key}",
        f"ANTHROPIC_API_KEY={anthropic_key}",
        "",
    ]

    # --- Step 3: Cloudflare Tunnel ---
    _print_step(3, total_steps, "リモートアクセス (Cloudflare Tunnel)")
    use_tunnel = _ask_yn("  Cloudflare Tunnel を使いますか?", default=False)
    tunnel_token = ""

    if use_tunnel:
        print("")
        print("  Tunnel トークンの取得方法:")
        print("    1. https://one.dash.cloudflare.com/ にログイン")
        print("    2. Networks > Tunnels > Create a tunnel")
        print("    3. Cloudflared を選択してトークンをコピー")
        print("")
        tunnel_token = _ask("  Tunnel Token (あとで設定する場合は空欄)")
        if not tunnel_token:
            print("  -> あとで .env に CLOUDFLARE_TUNNEL_TOKEN= を追加してください。")
            use_tunnel = False
    print("")

    env_lines += [
        "# --- Cloudflare Tunnel ---",
        f"CLOUDFLARE_TUNNEL_TOKEN={tunnel_token}",
        "",
    ]

    # --- Step 4: Network ---
    _print_step(4, total_steps, "ネットワーク")
    pbx_addr = _ask("  PBX バインドアドレス", default="0.0.0.0")
    print("")

    if pbx_addr != "0.0.0.0":
        env_lines += [
            "# --- Network ---",
            f"PBX_BIND_ADDRESS={pbx_addr}",
            "",
        ]

    # --- Write .env ---
    env_path.write_text("\n".join(env_lines) + "\n")
    env_path.chmod(0o600)

    print("  ┌─────────────────────────────────┐")
    print("  │         セットアップ完了          │")
    print("  └─────────────────────────────────┘")
    print("")
    print(f"  管理者パスワード: {admin_password}")
    print(f"  設定ファイル:     {env_path}")
    print("")

    # --- Start? ---
    _maybe_start(use_tunnel=use_tunnel)


def _maybe_start(use_tunnel: bool = False) -> None:
    compose = _find_compose()
    if not compose:
        print("  Docker が見つかりません。")
        print("  Docker をインストールしてから以下を実行:")
        print("    docker compose up -d")
        return

    if not _ask_yn("  今すぐ起動しますか?"):
        print("")
        print("  あとで起動するには:")
        if use_tunnel:
            print("    docker compose --profile tunnel up -d")
        else:
            print("    docker compose up -d")
        return

    print("")
    print("  起動中...")
    cmd = [*compose, "up", "-d", "--build"]
    if use_tunnel:
        cmd = [*compose, "--profile", "tunnel", "up", "-d", "--build"]

    result = _run(cmd)
    if result.returncode == 0:
        print("")
        print("  Millicall PBX が起動しました!")
        print("  Web UI: http://localhost")
        print("")
        print("  ログ確認:  docker compose logs -f millicall")
    else:
        sys.exit(result.returncode)


# ---------------------------------------------------------------------------
# Management commands
# ---------------------------------------------------------------------------


def cmd_start() -> None:
    compose = _find_compose()
    if not compose:
        print("Error: docker compose not found.")
        sys.exit(1)

    # Detect if tunnel is configured
    env_path = PROJECT_ROOT / ".env"
    use_tunnel = False
    if env_path.exists():
        content = env_path.read_text()
        for line in content.splitlines():
            if line.startswith("CLOUDFLARE_TUNNEL_TOKEN=") and line.split("=", 1)[1].strip():
                use_tunnel = True
                break

    cmd = [*compose, "up", "-d", "--build"]
    if use_tunnel:
        cmd = [*compose, "--profile", "tunnel", "up", "-d", "--build"]
        print("Starting Millicall PBX (with Cloudflare Tunnel)...")
    else:
        print("Starting Millicall PBX...")

    result = _run(cmd)
    if result.returncode == 0:
        print("")
        print("  Web UI: http://localhost")
        if not env_path.exists():
            print("")
            print("  .env がないため自動生成されたシークレットを使用中。")
            print("  パスワード確認: docker compose logs millicall 2>&1 | grep ADMIN_PASSWORD")
    sys.exit(result.returncode)


def cmd_stop() -> None:
    compose = _find_compose()
    if not compose:
        print("Error: docker compose not found.")
        sys.exit(1)
    _run([*compose, "--profile", "tunnel", "down"])


def cmd_logs() -> None:
    compose = _find_compose()
    if not compose:
        print("Error: docker compose not found.")
        sys.exit(1)
    with contextlib.suppress(KeyboardInterrupt):
        _run([*compose, "logs", "-f", "--tail", "100"])


def cmd_status() -> None:
    compose = _find_compose()
    if not compose:
        print("Error: docker compose not found.")
        sys.exit(1)
    _run([*compose, "ps", "-a"])


async def generate_config() -> None:
    """Generate Asterisk config files from database."""
    from millicall.infrastructure.asterisk.config_writer import AsteriskConfigWriter
    from millicall.infrastructure.database import async_session, engine
    from millicall.infrastructure.orm import metadata
    from millicall.infrastructure.repositories.extension_repo import ExtensionRepository
    from millicall.infrastructure.repositories.peer_repo import PeerRepository
    from millicall.infrastructure.repositories.trunk_repo import TrunkRepository

    async with engine.begin() as conn:
        await conn.run_sync(metadata.create_all)

    async with async_session() as session:
        ext_repo = ExtensionRepository(session)
        peer_repo = PeerRepository(session)
        trunk_repo = TrunkRepository(session)

        extensions = await ext_repo.get_all()
        peers = await peer_repo.get_all()
        trunks = await trunk_repo.get_all_enabled()

    peer_map = {p.id: p for p in peers if p.id is not None}
    writer = AsteriskConfigWriter()
    writer.write_pjsip_config(peers, trunks=trunks)
    writer.write_extensions_config(extensions, peer_map, trunks=trunks)
    writer.write_ari_config()
    logger.info("Asterisk config files generated successfully")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

USAGE = """\
Millicall PBX

Usage: millicall <command>

Commands:
  setup             Interactive setup wizard
  start             Build and start services (auto-detects tunnel)
  stop              Stop all services
  logs              Follow service logs
  status            Show service status
  generate-config   Generate Asterisk config from DB

Quick start:
  millicall setup
"""


def main() -> None:
    command = sys.argv[1] if len(sys.argv) > 1 else "setup"

    commands: dict[str, Callable[[], None]] = {
        "setup": cmd_setup,
        "init": cmd_setup,
        "start": cmd_start,
        "stop": cmd_stop,
        "logs": cmd_logs,
        "status": cmd_status,
        "generate-config": lambda: asyncio.run(generate_config()),
        "help": lambda: print(USAGE),
        "--help": lambda: print(USAGE),
        "-h": lambda: print(USAGE),
    }

    handler = commands.get(command)
    if handler:
        handler()
    else:
        print(f"Unknown command: {command}")
        print(USAGE)
        sys.exit(1)


if __name__ == "__main__":
    main()
