/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TrunksRouteImport } from './routes/trunks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PeersRouteImport } from './routes/peers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as CdrRouteImport } from './routes/cdr'
import { Route as CallHistoryRouteImport } from './routes/call-history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsNewRouteImport } from './routes/workflows_.new'
import { Route as TrunksNewRouteImport } from './routes/trunks_.new'
import { Route as PeersNewRouteImport } from './routes/peers_.new'
import { Route as ExtensionsNewRouteImport } from './routes/extensions_.new'
import { Route as CallHistoryLogIdRouteImport } from './routes/call-history_.$logId'
import { Route as WorkflowsWorkflowIdEditRouteImport } from './routes/workflows_.$workflowId.edit'
import { Route as TrunksTrunkIdEditRouteImport } from './routes/trunks_.$trunkId.edit'
import { Route as PeersPeerIdEditRouteImport } from './routes/peers_.$peerId.edit'
import { Route as ExtensionsExtensionIdEditRouteImport } from './routes/extensions_.$extensionId.edit'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TrunksRoute = TrunksRouteImport.update({
  id: '/trunks',
  path: '/trunks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersRoute = PeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const CdrRoute = CdrRouteImport.update({
  id: '/cdr',
  path: '/cdr',
  getParentRoute: () => rootRouteImport,
} as any)
const CallHistoryRoute = CallHistoryRouteImport.update({
  id: '/call-history',
  path: '/call-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/workflows_/new',
  path: '/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrunksNewRoute = TrunksNewRouteImport.update({
  id: '/trunks_/new',
  path: '/trunks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersNewRoute = PeersNewRouteImport.update({
  id: '/peers_/new',
  path: '/peers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsNewRoute = ExtensionsNewRouteImport.update({
  id: '/extensions_/new',
  path: '/extensions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CallHistoryLogIdRoute = CallHistoryLogIdRouteImport.update({
  id: '/call-history_/$logId',
  path: '/call-history/$logId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdEditRoute = WorkflowsWorkflowIdEditRouteImport.update({
  id: '/workflows_/$workflowId/edit',
  path: '/workflows/$workflowId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TrunksTrunkIdEditRoute = TrunksTrunkIdEditRouteImport.update({
  id: '/trunks_/$trunkId/edit',
  path: '/trunks/$trunkId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersPeerIdEditRoute = PeersPeerIdEditRouteImport.update({
  id: '/peers_/$peerId/edit',
  path: '/peers/$peerId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsExtensionIdEditRoute =
  ExtensionsExtensionIdEditRouteImport.update({
    id: '/extensions_/$extensionId/edit',
    path: '/extensions/$extensionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call-history': typeof CallHistoryRoute
  '/cdr': typeof CdrRoute
  '/devices': typeof DevicesRoute
  '/extensions': typeof ExtensionsRoute
  '/login': typeof LoginRoute
  '/peers': typeof PeersRoute
  '/settings': typeof SettingsRoute
  '/trunks': typeof TrunksRoute
  '/workflows': typeof WorkflowsRoute
  '/call-history/$logId': typeof CallHistoryLogIdRoute
  '/extensions/new': typeof ExtensionsNewRoute
  '/peers/new': typeof PeersNewRoute
  '/trunks/new': typeof TrunksNewRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/extensions/$extensionId/edit': typeof ExtensionsExtensionIdEditRoute
  '/peers/$peerId/edit': typeof PeersPeerIdEditRoute
  '/trunks/$trunkId/edit': typeof TrunksTrunkIdEditRoute
  '/workflows/$workflowId/edit': typeof WorkflowsWorkflowIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call-history': typeof CallHistoryRoute
  '/cdr': typeof CdrRoute
  '/devices': typeof DevicesRoute
  '/extensions': typeof ExtensionsRoute
  '/login': typeof LoginRoute
  '/peers': typeof PeersRoute
  '/settings': typeof SettingsRoute
  '/trunks': typeof TrunksRoute
  '/workflows': typeof WorkflowsRoute
  '/call-history/$logId': typeof CallHistoryLogIdRoute
  '/extensions/new': typeof ExtensionsNewRoute
  '/peers/new': typeof PeersNewRoute
  '/trunks/new': typeof TrunksNewRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/extensions/$extensionId/edit': typeof ExtensionsExtensionIdEditRoute
  '/peers/$peerId/edit': typeof PeersPeerIdEditRoute
  '/trunks/$trunkId/edit': typeof TrunksTrunkIdEditRoute
  '/workflows/$workflowId/edit': typeof WorkflowsWorkflowIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call-history': typeof CallHistoryRoute
  '/cdr': typeof CdrRoute
  '/devices': typeof DevicesRoute
  '/extensions': typeof ExtensionsRoute
  '/login': typeof LoginRoute
  '/peers': typeof PeersRoute
  '/settings': typeof SettingsRoute
  '/trunks': typeof TrunksRoute
  '/workflows': typeof WorkflowsRoute
  '/call-history_/$logId': typeof CallHistoryLogIdRoute
  '/extensions_/new': typeof ExtensionsNewRoute
  '/peers_/new': typeof PeersNewRoute
  '/trunks_/new': typeof TrunksNewRoute
  '/workflows_/new': typeof WorkflowsNewRoute
  '/extensions_/$extensionId/edit': typeof ExtensionsExtensionIdEditRoute
  '/peers_/$peerId/edit': typeof PeersPeerIdEditRoute
  '/trunks_/$trunkId/edit': typeof TrunksTrunkIdEditRoute
  '/workflows_/$workflowId/edit': typeof WorkflowsWorkflowIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call-history'
    | '/cdr'
    | '/devices'
    | '/extensions'
    | '/login'
    | '/peers'
    | '/settings'
    | '/trunks'
    | '/workflows'
    | '/call-history/$logId'
    | '/extensions/new'
    | '/peers/new'
    | '/trunks/new'
    | '/workflows/new'
    | '/extensions/$extensionId/edit'
    | '/peers/$peerId/edit'
    | '/trunks/$trunkId/edit'
    | '/workflows/$workflowId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call-history'
    | '/cdr'
    | '/devices'
    | '/extensions'
    | '/login'
    | '/peers'
    | '/settings'
    | '/trunks'
    | '/workflows'
    | '/call-history/$logId'
    | '/extensions/new'
    | '/peers/new'
    | '/trunks/new'
    | '/workflows/new'
    | '/extensions/$extensionId/edit'
    | '/peers/$peerId/edit'
    | '/trunks/$trunkId/edit'
    | '/workflows/$workflowId/edit'
  id:
    | '__root__'
    | '/'
    | '/call-history'
    | '/cdr'
    | '/devices'
    | '/extensions'
    | '/login'
    | '/peers'
    | '/settings'
    | '/trunks'
    | '/workflows'
    | '/call-history_/$logId'
    | '/extensions_/new'
    | '/peers_/new'
    | '/trunks_/new'
    | '/workflows_/new'
    | '/extensions_/$extensionId/edit'
    | '/peers_/$peerId/edit'
    | '/trunks_/$trunkId/edit'
    | '/workflows_/$workflowId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallHistoryRoute: typeof CallHistoryRoute
  CdrRoute: typeof CdrRoute
  DevicesRoute: typeof DevicesRoute
  ExtensionsRoute: typeof ExtensionsRoute
  LoginRoute: typeof LoginRoute
  PeersRoute: typeof PeersRoute
  SettingsRoute: typeof SettingsRoute
  TrunksRoute: typeof TrunksRoute
  WorkflowsRoute: typeof WorkflowsRoute
  CallHistoryLogIdRoute: typeof CallHistoryLogIdRoute
  ExtensionsNewRoute: typeof ExtensionsNewRoute
  PeersNewRoute: typeof PeersNewRoute
  TrunksNewRoute: typeof TrunksNewRoute
  WorkflowsNewRoute: typeof WorkflowsNewRoute
  ExtensionsExtensionIdEditRoute: typeof ExtensionsExtensionIdEditRoute
  PeersPeerIdEditRoute: typeof PeersPeerIdEditRoute
  TrunksTrunkIdEditRoute: typeof TrunksTrunkIdEditRoute
  WorkflowsWorkflowIdEditRoute: typeof WorkflowsWorkflowIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trunks': {
      id: '/trunks'
      path: '/trunks'
      fullPath: '/trunks'
      preLoaderRoute: typeof TrunksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers': {
      id: '/peers'
      path: '/peers'
      fullPath: '/peers'
      preLoaderRoute: typeof PeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdr': {
      id: '/cdr'
      path: '/cdr'
      fullPath: '/cdr'
      preLoaderRoute: typeof CdrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-history': {
      id: '/call-history'
      path: '/call-history'
      fullPath: '/call-history'
      preLoaderRoute: typeof CallHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/new': {
      id: '/workflows_/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof WorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trunks_/new': {
      id: '/trunks_/new'
      path: '/trunks/new'
      fullPath: '/trunks/new'
      preLoaderRoute: typeof TrunksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers_/new': {
      id: '/peers_/new'
      path: '/peers/new'
      fullPath: '/peers/new'
      preLoaderRoute: typeof PeersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions_/new': {
      id: '/extensions_/new'
      path: '/extensions/new'
      fullPath: '/extensions/new'
      preLoaderRoute: typeof ExtensionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-history_/$logId': {
      id: '/call-history_/$logId'
      path: '/call-history/$logId'
      fullPath: '/call-history/$logId'
      preLoaderRoute: typeof CallHistoryLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/$workflowId/edit': {
      id: '/workflows_/$workflowId/edit'
      path: '/workflows/$workflowId/edit'
      fullPath: '/workflows/$workflowId/edit'
      preLoaderRoute: typeof WorkflowsWorkflowIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trunks_/$trunkId/edit': {
      id: '/trunks_/$trunkId/edit'
      path: '/trunks/$trunkId/edit'
      fullPath: '/trunks/$trunkId/edit'
      preLoaderRoute: typeof TrunksTrunkIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers_/$peerId/edit': {
      id: '/peers_/$peerId/edit'
      path: '/peers/$peerId/edit'
      fullPath: '/peers/$peerId/edit'
      preLoaderRoute: typeof PeersPeerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions_/$extensionId/edit': {
      id: '/extensions_/$extensionId/edit'
      path: '/extensions/$extensionId/edit'
      fullPath: '/extensions/$extensionId/edit'
      preLoaderRoute: typeof ExtensionsExtensionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallHistoryRoute: CallHistoryRoute,
  CdrRoute: CdrRoute,
  DevicesRoute: DevicesRoute,
  ExtensionsRoute: ExtensionsRoute,
  LoginRoute: LoginRoute,
  PeersRoute: PeersRoute,
  SettingsRoute: SettingsRoute,
  TrunksRoute: TrunksRoute,
  WorkflowsRoute: WorkflowsRoute,
  CallHistoryLogIdRoute: CallHistoryLogIdRoute,
  ExtensionsNewRoute: ExtensionsNewRoute,
  PeersNewRoute: PeersNewRoute,
  TrunksNewRoute: TrunksNewRoute,
  WorkflowsNewRoute: WorkflowsNewRoute,
  ExtensionsExtensionIdEditRoute: ExtensionsExtensionIdEditRoute,
  PeersPeerIdEditRoute: PeersPeerIdEditRoute,
  TrunksTrunkIdEditRoute: TrunksTrunkIdEditRoute,
  WorkflowsWorkflowIdEditRoute: WorkflowsWorkflowIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
